package com.bortxapps.goprocontrollerandroid.exposedapi

import com.bortxapps.goprocontrollerandroid.domain.contracts.GoProCommands
import com.bortxapps.goprocontrollerandroid.domain.contracts.GoProConnector
import com.bortxapps.goprocontrollerandroid.domain.contracts.GoProMedia

interface GoProController: GoProMedia, GoProCommands, GoProConnector